nickslick03/messiah-meal-planner

- src/App.tsx
- src/components/containers/ModalContainer.tsx
- src/components/containers/ScreenContainer.tsx
- src/components/containers/SectionContainer.tsx
- src/components/containers/table/ButtonCell.tsx
- src/components/containers/table/TableCell.tsx
- src/index.css
- src/lib/constants.ts
- tailwind.config.js
added custom messiah colors and font to tailwind config
> Custom styles

- src/components/form_elements/Input.tsx
> added flex-wrap to input elements

- src/App.tsx
- src/components/containers/MealContainer.tsx
- src/components/containers/ModalContainer.tsx
- src/components/containers/ScreenContainer.tsx
- src/components/containers/SectionContainer.tsx
- src/components/containers/table/MealTable.tsx
- src/components/form_elements/Input.tsx
- src/components/form_elements/Select.tsx
- src/components/modals/CustomMealAddModal.tsx
- src/components/modals/SortingModal.tsx
- src/components/other/CustomMeal.tsx
- src/components/other/Divider.tsx
- src/components/other/DotLeader.tsx
- src/components/sections/AvailableMeals.tsx
- src/components/sections/DayEditor.tsx
- src/components/sections/MealQueue.tsx
- src/static/constants.ts
I created MealQueue and DayEditor. Let me know what you think.
> Bottom half of frontend (MealQueue and DayEditor)

- src/App.tsx
- src/components/containers/ModalContainer.tsx
- src/components/containers/table/MealTable.tsx
- src/components/form_elements/Input.tsx
- src/components/sections/DayEditor.tsx
- src/components/sections/Results.tsx
- src/static/mealsDatabase.ts
Made *most* of the UI changes discussed. I decided it would be better to keep the original height of the modal since it looks weird when it's short. I also added the meals database as an array of meal objects.
> UI touch and json

- src/components/containers/MealContainer.tsx
- src/components/containers/table/MealTable.tsx
- src/components/other/Notification.tsx
- src/components/sections/AvailableMeals.tsx
- src/components/sections/DayEditor.tsx
- src/components/sections/MealQueue.tsx
- src/components/sections/ResultsBar.tsx
- tailwind.config.js
Notifications now pop up whenever a meal button is clicked. There's one notification component per meal table, so if multiple meals are clicked in the same table within the time it takes the animation to complete, the notification bar resets instead of another notification appearing. I think it's fine, but if you would rather have an individual notification component per meal row, we can do that too. We could also add notifications for other buttons as well. Let me know your thoughts.
> Notifications

- src/components/containers/MealContainer.tsx
- src/components/containers/table/MealTable.tsx
- src/components/other/Notification.tsx
- src/components/sections/AvailableMeals.tsx
- src/components/sections/DayEditor.tsx
- src/components/sections/MealQueue.tsx
- src/components/sections/ResultsBar.tsx
- src/lib/sortMeals.ts
- src/test/sortMeals.test.ts
- src/types/SortBy.ts
- tailwind.config.js
Added sorting logic. Not entirely sure how it should behave though. As of now, the sorting preferences do not persist due to the current scope of the sorting variables as state in the MealContainer (which will not work for this given the way localStorage works, we would need to refactor if we want this). The user also must sort each table individually, not sure if this control is the best or if it would be better if all the tables sorted automatically the same way based on a global setting, or maybe if there would be a "sort all tables" checkbox in the modal. Thoughts on these issues?
> Added sorting logic and associated unit test

- src/App.tsx
- src/components/containers/MealContainer.tsx
- src/components/containers/table/MealTable.tsx
- src/components/containers/table/TableCell.tsx
- src/components/containers/table/TableRow.tsx
- src/components/modals/CustomMealAddModal.tsx
- src/components/other/CustomMeal.tsx
- src/components/sections/AvailableMeals.tsx
- src/static/context.ts
- src/types/Meal.ts
- tailwind.config.js
Reverts nickslick03/messiah-meal-planner#27 Not sure why this merged, I don't think I did anything. Undoing...
> Revert "Added custom meal editor."

- package-lock.json
- package.json
- src/App.tsx
- src/components/sections/AvailableMeals.tsx
- src/components/sections/DayEditor.tsx
- src/components/sections/MealQueue.tsx
- src/static/context.ts
- src/static/mealsDatabase.ts
- src/types/Meal.ts
- src/types/MealReference.ts
- src/types/userSelectedMealsObject.ts
Refactored the program so that userSelectedMeals and mealQueue just have references to the available meal arrays, and added memos to dereference them. Everything should now sync up with the common copy of meals, including custom meals.
> Synchronization with available meals

- src/components/containers/table/TableRow.tsx
- src/components/sections/DayEditor.tsx
- src/components/sections/Results.tsx
- src/components/sections/ResultsBar.tsx
- src/lib/calculationEngine.ts
- src/lib/dateCalcuation.ts
- src/lib/dateFormatter.ts
- src/lib/formatCurrency.ts
- src/lib/mealsIndex.ts
- src/static/constants.ts
- src/static/discounts.ts
- src/test/calculationEngine.test.ts
- src/test/dateCalculation.test.ts
- src/test/mealsIndex.test.ts
I created the timing and meal total functions with unit tests and hooked them to their respective components. I also made a mealIndex object that links the meal IDs to its index so the Array.find() function doesn't have to be called on the meal references to find its corresponding meal (check out implementation in the getMealTotal function in calculationEngine.ts). If you prefer this method of meal lookup, perhaps you'll want to refactor the code that uses .find()? Let me know what you think about that and the rest of the PR.
> Date and total calculations

- src/App.tsx
- src/components/form_elements/Input.tsx
- src/components/sections/MealPlanInfo.tsx
- src/static/context.ts
Validation on the 1-week break checkbox. Added possibility of null boolean values (which actually simplified the Input component) and updated the validator function to check the date difference. I didn't modify any of the same stuff as the search PR, so if everything is working properly we should be able to merge both in when they're ready without complications.
> Added validation on the 1-week break checkbox

- src/components/sections/MealQueue.tsx
- src/static/mealsDatabase.ts
mealQueue now displays when a user tries to add a meal to a day in which the meal's location is closed.
> added closed location guard

- src/components/sections/Results.tsx
Quick fix to get the results help button working.
> Fixed results help button

- src/components/sections/Results.tsx
> added week total message

- src/components/containers/ModalContainer.tsx
- src/components/containers/table/ButtonCell.tsx
- src/components/containers/table/MealTable.tsx
- src/components/containers/table/TableCell.tsx
- src/components/form_elements/Button.tsx
- src/components/form_elements/DaySelector.tsx
- src/components/modals/CustomMealAddModal.tsx
- src/components/other/Highlighter.tsx
- src/components/other/Notification.tsx
- src/components/sections/DayEditor.tsx
- src/components/sections/MealQueue.tsx
- src/components/sections/Results.tsx
- src/components/sections/ResultsBar.tsx
Added css animations. Color changes now have a fade effect and the selectors now slide. There is a bit of weirdness as I had to put a manual vertical offset on the highlighter component to get it to display properly on the MealTable, but it works.
> Animations

- src/App.tsx
- src/components/form_elements/Input.tsx
- src/components/sections/DayEditor.tsx
- src/components/sections/MealPlanInfo.tsx
- src/components/sections/Results.tsx
- src/lib/calculationEngine.ts
- src/lib/dateCalcuation.ts
- src/static/context.ts
- src/static/tutorial.tsx
- src/test/calculationEngine.test.ts
- src/test/dateCalculation.test.ts
- src/test/filterMeals.test.ts
Changed the isBreak checkbox to weeksOff number when calculating the total cost. I noticed a couple of weeks I want to ask about:
- at around line 242 of results.tsx you put another dot leader row titled "Date when money runs out," and you had a ternary "(assuming your break is before this)." But now that the the dayWhenRunOut function accounts for the weekOff, or now weeksOff, this clause is obsolete, right?
- at line 72 in calculationEngine.ts, in the function calculateDateWhenRunOut, you put a .slice(7) call on the dates array when isBreak is true. Reading the documentation says that the slice function takes an index, not the number of elements to be removed, so should it be 6 instead?
> Multiple weeks off

- src/App.tsx
- src/components/containers/ModalContainer.tsx
- src/components/modals/ResetModal.tsx
- src/components/other/Menu.tsx
- src/static/tutorialSteps.tsx
Added a menu sidebar that has a reset option. At the bottom of the menu sidebar is a credits footer. You can link your name to whatever you'd like.
> Menu sidebar

- src/components/containers/table/MealTable.tsx
- src/components/form_elements/Input.tsx
The title says it all, haha...search bar now clearable. Implements #50.
> Added clear button to search bar.

- src/components/containers/ModalContainer.tsx
- src/components/containers/table/MealTable.tsx
- src/components/modals/PresetMealPlanModal.tsx
- src/components/other/Menu.tsx
- src/components/other/Notification.tsx
- src/components/other/PresetMealPlanView.tsx
- src/static/PresetMealPlans.ts
- src/static/mealsDatabase.ts
- tailwind.config.js
preset meal plans can be found in the menu section. So far there are two presets.
> preset meal plans

- src/components/sections/Results.tsx
- src/lib/calculationEngine.ts
Implemented error handler to guard against feeding severely distanced dates into the ```getAllDatesBetween``` function. Fixes #56.
> Fixed recursion depth error on date calcuation

- src/components/containers/table/ButtonCell.tsx
- src/components/containers/table/TableRow.tsx
- src/components/sections/MealQueue.tsx
- src/static/mealsDatabase.ts
- src/types/Meal.ts
Meals can now have unavailable days. This is validated in the meal queue and now both unavailable meals and locations cannot be added directly from the 'available meals' section.
> Mmp 104 meal closures

- src/components/modals/Tutorial.tsx
- src/components/other/BetaNotice.tsx
- src/components/other/Menu.tsx
- src/static/tutorialSteps.tsx
I've added a beta notice to both the first screen on the tutorial and the menu, so if people hear about the app indirectly they realize we are just at the production phase and haven't tested it widely yet. It also contains a link to a suggestion form that uses a Google Apps Script to forward the response to Jira and create an issue. It's restricted to Messiah emails only. Unfortunately I can't share the script because it contains my Jira API key which is effectively a password to my entire Jira account, but it's not overly complicated.
> MMP-107: Beta notice and bug suggestion reporting

- src/components/modals/LocationHoursModal.tsx
- src/components/other/Menu.tsx
- src/static/locationHours.ts
there now exists a location hours modal in the menu sidebar
> Location hours

- src/components/sections/DayEditor.tsx
buttons to clear user selected meals in day editor
> Clear user selected meals

- src/components/modals/LocationHoursModal.tsx
- src/components/modals/PresetMealPlanModal.tsx
- src/components/other/PresetMealPlanView.tsx
I know merging to master is a big no no but the overflow in the menu modals wasn't fully visible and I'd like it to look nice for tonight, these changes should only effect the styling.
> fixed overflow in menu modals

- src/static/mealsDatabase.ts
Union menu and prices are now updated for the new school year
> Updated Union Menu

- src/static/mealsDatabase.ts
- src/static/releaseNotes.ts
Fixed the price of Union Acai bowls (it's also updated in the google sheet)
> MMP-140-union-acai-bowl-price-fix

- src/components/containers/ModalContainer.tsx
- src/components/modals/CustomMealAddModal.tsx
- src/components/modals/Tutorial.tsx
- src/components/other/CustomMeal.tsx
- src/components/sections/AvailableMeals.tsx
- src/components/sections/DayEditor.tsx
- src/static/releaseNotes.ts
changed the z indexes of the tutorial textbox, custom meal modal, and some confirmation modals in the main section areas.
> Mmp 132 notification tutorial zindex

- src/App.tsx
- src/components/containers/table/ButtonCell.tsx
- src/components/containers/table/TableRow.tsx
- src/components/modals/Tutorial.tsx
- src/components/other/ContextProvider.tsx
- src/components/other/Menu.tsx
- src/hooks/useLongPress.ts
- src/hooks/usePersistentState.ts
- src/lib/isMobile.ts
- src/static/context.ts
- src/static/tutorialSteps.tsx
Meal queue is now hidden by default but can be toggled via a switch in the menu
> MMP-148-toggle-showing-meal-queue-1.0.0

- src/App.tsx
- src/components/modals/InvalidModal.tsx
- src/static/mealsDatabase.ts
The default values for the initial balance and weeks off pulls from the google spreadsheet. The different sheets are accessed by changing the "entity" query parameter in the URL, and the Appscript script has been updated accordingly. Fun note, I tried doing different paths in the URL but I got a bunch of CORS errors and couldn't fix them without changing from URL paths to URL parameters.
> added default values to meal plan

- LICENSE
- ThirdPartyNotices.txt
- package-lock.json
- package.json
- src/components/other/Menu.tsx
- src/static/releaseNotes.ts
- src/static/tutorialSteps.tsx
With this PR, the project will be officially licensed under the MIT license. I've also added links to it (they won't work until we push to master though) and a link to the feedback form, and removed the beta notice. I've also taken the opportunity to update some dependencies that were out of date enough to have some security issues, run npm install to update them.
> Added license and links to it, updated deps, added feedback link, and removed beta notice

- README.md
- package.json
Updated the readme! After this PR is merged, we can merge into master and deploy version 1.0.0 to GitHub pages!
> MMP-149 Update README

- package-lock.json
- src/components/containers/table/ButtonCell.tsx
- src/components/other/Menu.tsx
The menu button in the corner disappearing when scrolling down actually really annoys me, I just made it visible no matter what.
> menu button in corner stays visible

- src/components/containers/table/ButtonCell.tsx
- src/components/containers/table/TableRow.tsx
There were some missing parentheses in the conditional, this adds them and thus fixes #99.
> Fixed broken delete button
